language: node_js
notifications:
 email: false
node_js:
 - "node"
before_script:
 - npm prune
script:
 - npm run lint
 - npm run test
 - npm run build:release
after_success:
  - npm run report-coverage